"""Replay all R1 checkpoints on CPU and independently check saved metrics.
This verifies artifact consistency, not scientific significance or SOTA status.
"""
from pathlib import Path
import hashlib, json, os, sys
import numpy as np
import torch
ROOT=Path(__file__).resolve().parents[1]
os.chdir(ROOT)
sys.path.insert(0,str(ROOT))
from scripts.audit_pilot import SharedDistance
from models.audit_cross_encoder import CrossEncoder
from utils.audit_protocol import assert_disjoint_od


def digest(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def raw_predict(model, mode, pairs, coords, scale):
    """Recompute the distance formulas explicitly, rather than reuse saved scores."""
    ij=np.vstack([pairs[:,:2],pairs[:,[1,0]]]).astype(np.int64)
    outputs=[]
    with torch.no_grad():
        if mode.startswith('shared_'):
            z=model.encode()
            for begin in range(0,len(ij),8192):
                batch=ij[begin:begin+8192]
                delta=z[batch[:,1]]-z[batch[:,0]]
                if mode=='shared_l1':
                    p=delta.abs().sum(1)
                elif mode=='shared_linf':
                    p=delta.max(1).values
                else:
                    r=63 if mode=='shared_tilde_63_1' else 62
                    p=delta[:,:r].abs().sum(1)+delta[:,r:].sum(1)
                outputs.append(p.numpy()*scale)
        else:
            c=(coords-coords.mean(0))/coords.std(0)
            for begin in range(0,len(ij),8192):
                batch=ij[begin:begin+8192]
                x=torch.from_numpy(np.hstack([c[batch[:,0]],c[batch[:,1]]]).astype(np.float32))
                out=model.head(model.backbone(x))
                if mode=='cross_scalar':
                    p=torch.nn.functional.softplus(out).flatten()
                else:
                    delta=out[:,64:]-out[:,:64]
                    if mode=='cross_l1':p=delta.abs().mean(1)
                    else:
                        r=2 if mode=='cross_tilde_2_62' else 62
                        p=(delta[:,:r].abs().sum(1)+delta[:,r:].sum(1))/64
                outputs.append(p.numpy()*scale)
    return np.concatenate(outputs)


def independent_metrics(pred,q):
    true=np.concatenate([q[:,2],q[:,3]])
    mre=100*np.mean(np.abs(pred-true)/true)
    mae=np.mean(np.abs(pred-true))
    n=len(q)
    ar=np.sqrt(np.mean(((pred[:n]-pred[n:])/2-(q[:,2]-q[:,3])/2)**2))
    return {'mre_percent':float(mre),'mae':float(mae),'directional_difference_rmse':float(ar)}


def main():
    torch.set_num_threads(2)
    report=ROOT/'reports/audit-r1-20260913'
    pilot=json.loads((report/'pilot.json').read_text())
    execution=json.loads((report/'pilot_execution.json').read_text())
    assert execution['exit_code']==0 and pilot['status']=='completed'
    assert pilot['completed_runs']==pilot['planned_runs']==24
    z=np.load('data/audit/protocol_r1/splits.npz')
    assert digest('data/audit/protocol_r1/splits.npz')==pilot['data_sha256']
    config=pilot['protocol']
    train=z['train'][:config['train_pairs']]
    val=z['validation'][:config['eval_pairs']]
    test=z['test'][:config['eval_pairs']]
    assert_disjoint_od(train,val,test)
    coords=z['coordinates']
    root=ROOT/'results/audit-r1-20260913/checkpoints'
    rows=[]
    identities=set()
    for run in pilot['results']:
        mode,seed=run['mode'],run['seed']
        assert (mode,seed) not in identities
        identities.add((mode,seed))
        path=root/f'{mode}_seed{seed}.pt'
        assert digest(path)==run['checkpoint_sha256']
        # These checkpoints were generated by this project in this task.
        ckpt=torch.load(path,map_location='cpu',weights_only=False)
        scale=ckpt['scale']
        assert scale==float(np.max(train[:,2:4]))
        if mode.startswith('shared_'):
            model=SharedDistance(coords,z['edges'],mode,hidden=ckpt['hidden'])
        else:
            name='scalar' if mode=='cross_scalar' else 'l1' if mode=='cross_l1' else 'l1tilde'
            r,s=(2,62) if mode=='cross_tilde_2_62' else (62,2)
            model=CrossEncoder(4,hidden=ckpt['hidden'],mode=name,r=r,s=s)
        model.load_state_dict(ckpt['state_dict']);model.eval()
        artifact=np.load(root/f'{mode}_seed{seed}_test.npz')
        np.testing.assert_array_equal(artifact['queries'],test)
        saved=artifact['predictions']
        replay=raw_predict(model,mode,test,coords,scale)
        np.testing.assert_allclose(replay,saved,rtol=2e-5,atol=.1)
        recalc=independent_metrics(saved,test)
        recorded=run['test']['all']
        for key,value in recalc.items():
            assert abs(value-recorded[key])<1e-3, (mode,seed,key,value,recorded[key])
        val_pred=raw_predict(model,mode,val,coords,scale)
        vm=independent_metrics(val_pred,val)['mre_percent']
        assert abs(vm-run['best_validation_mre_percent'])<.002, (mode,seed,vm)
        assert ckpt['best_validation_epoch']==run['best_validation_epoch']
        assert run['best_validation_mre_percent']==min(x['validation_mre_percent'] for x in run['history'])
        rows.append({'mode':mode,'seed':seed,'test_mre_percent':recalc['mre_percent'],
                     'cpu_vs_gpu_prediction_max_abs_difference':float(np.max(np.abs(replay-saved))),
                     'cpu_replayed_validation_mre_percent':vm,
                     'validation_mre_replay_difference_pp':abs(vm-run['best_validation_mre_percent']),
                     'checkpoint_sha256':digest(path)})
        print('REPLAY_OK',mode,seed,flush=True)
    result={'status':'passed','runs':len(rows),'device':'cpu',
            'method':'load trained checkpoint in a new process, recompute decoder formulas and raw prediction metrics',
            'tolerance_prediction':{'rtol':2e-5,'atol_distance_units':.1},
            'tolerance_validation_mre_pp':.002,'rows':rows,
            'scope':'artifact consistency only; not an independent dataset replication or significance test'}
    (report/'checkpoint_replay.json').write_text(json.dumps(result,indent=2)+'\n')
    diagnostic=json.loads((report/'diagnostic_chengdu.json').read_text())
    d=diagnostic['split_metrics']['test']
    lines=['# 路网距离项目 R1：部署、修复与小规模验证','',
        '## 已完成','',
        '- 服务器：4090；工作目录 `/workspace/distance`。',
        '- 源版本：`VLDB@c4fb479`；修改保存在 `research/l1tilde-audit-20260913`，未改原始 VLDB/main。',
        '- 项目环境 `.venv-audit`；23 项回归测试通过，RTX 4090 前向/反向测试通过。',
        '- 原实现的 GNN 旁路、landmark 标签错配、Cross-Encoder 维数反转均有可执行复现记录。',
        '- 独立 Dijkstra 全矩阵验证通过：1,901 节点、5,941 有向边，最大差异 0。',
        '- 8 配置 × 3 随机种子 = 24 组探索实验完成；24 个 checkpoint 已在 CPU 新进程重放。','',
        '## 方向性诊断（不是学习模型精度）','',
        f"测试查询中非对称程度 <1% 的比例为 {100*d['asymmetry_lt_1pct_fraction']:.3f}%；≥20% 的比例为 {100*d['asymmetry_ge_20pct_fraction']:.3f}%。",
        f"仅由训练查询拟合的节点势差解释了 {100*d['all']['potential_explained_energy_ratio_vs_zero']:.3f}% 的测试方向差平方能量。短距离切片为 {100*d['short_train_q25']['potential_explained_energy_ratio_vs_zero']:.3f}%。",
        f"在已知真实对称分量 S 的诊断中，中点参考 MRE={d['all']['oracle_symmetric_midpoint_mre_percent']:.6f}%，加上 L2 拟合势差后 MRE={d['all']['oracle_S_plus_train_fitted_potential_mre_percent']:.6f}%。这不是已训练索引的分数，也不是势差在 MRE 目标下的最优值。",'',
        '## 小规模探索结果','',
        '训练/验证/测试分别为 20,000/5,000/5,000 个无序 OD 对，每对包含两个方向；固定 30 epochs、hidden=128，三个种子。仅验证集选择 checkpoint。',
        '| 配置 | 平均测试 MRE（%） | 种子间样本标准差（百分点） |','|---|---:|---:|']
    for mode,s in pilot['summary'].items():
        lines.append(f"| {mode} | {s['mean_test_mre_percent']:.6f} | {s['std_test_mre_pp']:.6f} |")
    lines+=['','## 解释边界与下一步','',
        '这份数据是仓库旧版成都 1,901 节点图，不是历史 Harbin/Beijing 实验数据。当前环境的限定范围检查未找到这两份历史查询快照，未使用新下载地图冒充历史数据。',
        '比较解码器应优先看同一编码器家族内的结果；两类编码器之间并不等价。2+62 是明确标记的参数化控制，不是 62+2 的实现。',
        '不把三个种子的小图探索当作显著性、SOTA、跨城市泛化或延迟结论；不按测试结果继续调参。',
        '下一阶段先接入确切的 Harbin/Beijing graph 与 query 快照，复用按无序 OD 分组的协议；检查短距离、高非对称查询的收益与方向误差，而不是直接扩大 GNN 结构搜索。',
        '历史重复目录 `ablation_study/models`、`original`、`modified` 仍为历史参考；审计后的执行入口为根目录 models/utils/train 以及 scripts/audit_pilot.py。']
    (report/'R1_STATUS_ZH.md').write_text('\n'.join(lines)+'\n')
    print('CHECKPOINT_REPLAY_COMPLETE',len(rows),flush=True)

if __name__=='__main__':main()
